// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

module.exports = {
  // Additional arguments to pass to VS Code
  launchArgs: [
    '--new-window',
    '--disable-extensions',
    '--no-sandbox'
  ],
}
          